pizza constructor
htmlacademy-vue/817677-pizza-1 pull request #1
Opened 2021-07-03 14:38 UTC by TenHiderovich

2021-07-03 15:27 UTC, Djaler requested changes

2021-07-03 15:27 UTC, Djaler commented on src/frontend/src/views/Index.vue
> +                  class="dough__input dough__input--light"
Класс `dough__input--light` должен быть не захардкожен, а выставляться в зависимости от типа теста (тонкое - light, толстое - large)

2021-07-03 15:27 UTC, Djaler commented on src/frontend/src/views/Index.vue
> +                  :key="index"
в случае наличия у объектов списка явно уникального значения, лучше использовать его для key. в нашем случае это name

2021-07-03 15:27 UTC, Djaler commented on src/frontend/src/views/Index.vue
> +                    checked
checked проставляется на все радио-баттоны. В оригинальном шаблоне выбран первый

2021-07-03 15:27 UTC, Djaler commented on src/frontend/src/views/Index.vue
> +                          :name="ingredient.filling"
у этого инпута name `counter` установлен в оригинальной верстке, а не в зависимости от ингридиента

2021-07-03 15:27 UTC, Djaler commented on src/frontend/src/common/helpers.js
> +    const values = {
Можно этот объект инвертировать, тогда будет сильно проще искать нужное значение

2021-07-03 16:28 UTC, Djaler commented on src/frontend/src/common/helpers.js
> +    const values = {
Я имел в виду прямо изначально объект объявить 
```
{
  "Томатный": "tomato",
  ...
}
```

2021-07-03 16:36 UTC, Djaler commented on src/frontend/package.json
> +    "prettier": "^2.3.2",
а зачем поднята версия prettier?

2021-07-03 16:36 UTC, Djaler commented on docker-compose.yml
> +      - /backend/node_modules
и вот это?

2021-07-04 01:22 UTC, TenHiderovich commented on src/frontend/package.json
> +    "prettier": "^2.3.2",
prettier не срабатывал, в консоли была ошибка что  модуль prettier не найден. Пробовал заходить в контейнер и устанавливать его отдельно, а так как пакет особо ни с чем не связан, то версию не стал прописывать ту же самую.

2021-07-04 01:22 UTC, TenHiderovich commented on docker-compose.yml
> +      - /backend/node_modules
Запуск через докер не работал. node_modules не появлялась в контейнере. В слаке посоветовали добавить эти строчки https://htmlacademy-vue.slack.com/archives/C025NBNCJ5Q/p1625299126095400?thread_ts=1625133906.069400&cid=C025NBNCJ5Q

2021-07-04 01:23 UTC, merged